### ISSUE TITLE
Spring 3 support?

### ISSUE THREAD

**Issue by achuinard** [KuliginStepan/mongration#23]
Hi there, I'm trying to upgrade to Spring 3 but get the following error at app startup:

```
java.lang.IllegalStateException: The following classes could not be excluded because they are not auto-configuration classes:
	- com.kuliginstepan.mongration.configuration.MongrationAutoConfiguration
	- com.kuliginstepan.mongration.actuator.MongrationActuatorAutoConfiguration
```

Have you seen this before?

**Comment by KuliginStepan** [comment]
Hi! Library is not yet compatible with Spring Boot 3. I will try to release new version with Spring Boot 3 support to the end of this week.

**Comment by achuinard** [comment]
That's awesome, thank you!

**Comment by KuliginStepan** [comment]
@achuinard mongration 2.0.0 with spring boot 3 support is available now!
