### ISSUE TITLE
Mongration is not picked up at startUp

### ISSUE THREAD

**Issue by mf81bln** [KuliginStepan/mongration#4]
I was really glad to read your post on medium.com regarding mongobee and to find out, that you have built a solution to work around the index problem. 🙂 

I tried to integrate your solution into my spring boot project. However, I was unable to get it running. As far as I understand the code and the Spring integration, this should be initialized without further configuration when starting the application using `MongrationAutoConfiguration`. Setting the option `mongration.enabled = true` didn't help.
Is there another configuration option/annotation I might have overlooked?

Thanks in advance for your support!

Best regards

**Comment by KuliginStepan** [comment]
Could you provide a sample project, which helps me reproduce this problem? Also, this version of Mongration is not so good (especially because of this workaround with indexes), so I am working on the totally new version now, which will depend on spring data 2.2.0. Spring Data 2.2.0 solves a problem with indexes creation, so Mongration will have a better design.

**Comment by mf81bln** [comment]
Wow, thanks for the ultra fast answer! 🙂 

I digged a little deeper and well... Mongration actually is picked up at application start, but it seems to be starting too late.

My issue is that a defined CompoundIndex should change. So I changed it on my entity from 
```
@CompoundIndex(
    name = "lang_comp_serv_exttmpl_idx",
    def = "{'language': 1, 'companyCode': 1, 'mailServiceProvider': 1, 'externalTemplateId': 1}",
    unique = true
)
```

to 

```
@CompoundIndex(
    name = "lang_proj_serv_exttmpl_idx",
    def = "{'language': 1, 'mailServiceProject': 1, 'mailServiceProvider': 1, 'externalTemplateId': 1}",
    unique = true
)
```

and renamed the entity field from `companyCode` to `mailServiceProject`.

But it seems like this annotation is processed by Spring during `MongoAutoConfiguration` - so Mongration comes after this. And during application start Spring tries to create the unique index on the (at this moment) not existing field `mailServiceProvider` and fails.

Are you aware of this problem? Or is there another problem that is fixed in Spring Data 2.2.0?

**Comment by KuliginStepan** [comment]
I checked your code and I understood your problem. When you change your index definition (especially name), you need to manually drop the previous index (for example, in your `@ChangeSet` you need to manually drop index with `MongoTemplate` and after this, you may insert data for the new index, which will be generated after migration will be executed). 
Spring only creates new indexes, but not deletes unused ones.

**Comment by KuliginStepan** [comment]
How do you do changeset? Do you rename field `companyCode` to `mailServiceProject` or just append a new field to the entity? If you rename this field and don't delete the previous index `lang_comp_serv_exttmpl_idx` in the same changeset when you will see DuplicateKeyException because of the previous index still on the entity.

**Comment by mf81bln** [comment]
Thx for your help. I found a way, to work around this. I've removed the annotation based index on my entity and changed the changeset like follows:

1) drop indexes on collection
2) apply changes
3) recreate indexes

This works for the current case - but it's still a workaround. But I'm fine with it for now.
Thanks again! 🙂

**Comment by KuliginStepan** [comment]
@mf81bln I am going to solve it in the next version.
