### ISSUE TITLE
Not working in my project

### ISSUE THREAD

**Issue by gyansatapathy** [KuliginStepan/mongration#6]
import com.kuliginstepan.mongration.annotation.Changelog;
                                              ^
  bad class file: C:\Users\gyans\.gradle\caches\modules-2\files-2.1\com.github.kuliginstepan\mongration\1.0.0\c0a9c75bd41963477ce1a99059b3b9261001e3ab\mongration-1.0.0.jar(com/kuliginstepan/mongration/annotation/Changelog.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by KuliginStepan** [comment]
Can you provide some information about your environment and how you import library?

**Comment by stevenhurth** [comment]
I had the same issue, and it turned out my runtime was targeted at Java 8, but Mongration appears to have been compiled with Java 11. After pointing my compiler to Java 12 - no more error.

**Comment by shurth** [comment]
Best I can tell, there's no reason for this to be JDK12. I'd suggest "downgrading" to JDK8 so it works with most DockerHub images.

**Comment by KuliginStepan** [comment]
@shurth I agree with you, but we need to rewrite some code to remove java 11 features
