### ISSUE TITLE
Multiple changelogs failure

### ISSUE THREAD

**Issue by orelgenya** [KuliginStepan/mongration#7]
It seems changelogs are processed concurrently which leads to `Mongration couldn't acquire process lock` exception. It could be reproduced by adding second changelog to ReactiveMongrationTest. 
Also it seems `ApplicationReadyEvent` is fired twice, so would be nice to have a protection from multiple execution.

**Comment by KuliginStepan** [comment]
@orelgenya thank you for issue. I will try to fix it as soon as possible

**Comment by KuliginStepan** [comment]
@orelgenya I fixed this issue with #8, but I couldn't reproduce the issue with several `ApplicationReadyEvent`. Can you provide a sample, which reproduces it?

**Comment by orelgenya** [comment]
I've just checked that an Exception during mongration process (e.g. in changeset) causes the event to be triggered twice. Even though it might be not critical in most cases there are others. See https://github.com/spring-projects/spring-boot/issues/8899
Also I guess that might happen when spring refreshable context feature is used.
